### ISSUE TITLE
Wrong path for Ansible in Vagranfile

### ISSUE THREAD

**Issue by vb** [roots/roots-example-project.com#12]
I get

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/viktor/sites/example.com/Vagrantfile
Message: ./group_vars/development file not found. Please set `ANSIBLE_PATH` in Vagrantfile

If you move the Vagrantfile to root directory (#5 in instructions) you'll have to update the ANSIBLE_PATH from '' to 'ansible' (the ansible directory name)

**Comment by swalkinshaw** [comment]
There's already a `Vagrantfile` in the root with the correct `ANSIBLE_PATH` set.

**Comment by swalkinshaw** [comment]
@viktorbergehall oh yes, the current README is missing the `ANSIBLE_PATH` part. I have an update almost ready where it won't be necessary to update that setting though. It will just detect it automatically.

**Comment by swalkinshaw** [comment]
Closed by #13
