### ISSUE TITLE
Ansible task failing - [php | Start php5-fpm service]

### ISSUE THREAD

**Issue by skinofstars** [roots/roots-example-project.com#16]
Ansible task failing

`TASK: [php | Start php5-fpm service]`

Also effects `NOTIFIED: [common | reload php-fpm]`

Oddly, starting the service manually works fine.

**Comment by Foxaii** [comment]
Please see: roots/bedrock-ansible/issues/205

**Comment by skinofstars** [comment]
@Foxaii right, thanks. Urgh... I'd actually got this to work on a subsequent run anyway. Good to see some details.
