### ISSUE TITLE
Can´t find "WP_DEFAULT_THEME" in "site/config/application.php"

### ISSUE THREAD

**Issue by pablopaul** [roots/roots-example-project.com#19]
https://github.com/roots/roots-example-project.com/blob/master/README.md#bedrock says:

> here's only one custom option set in this example: WP_DEFAULT_THEME

but I can´t find it in the application.php file and sage is not the default theme.

**Comment by swalkinshaw** [comment]
Thanks for noticing this. It was just lost during an update.

**Comment by pablopaul** [comment]
Thanks for the immediate fix ;-)

**Comment by sooraj20890** [comment]
@swalkinshaw hi scott
i know its the wrong project for asking this question.
got your info from github.
Sorry if I disturb you.
 am trying to use capistrano to sort of run sidekiq jobs on servers
I have this in settings.rb file

role :unicorn, *(1..3).map { |i| "node#{i.to_s.rjust(2,'0')}.playdrone.io" }

role :sidekiq, *(1..3).map { |i| "node#{i.to_s.rjust(2,'0')}.playdrone.io" }

role :metrics, 'node01.playdrone.io'

role :master, 'node01.playdrone.io'

but when i install capistrano and run cap deploy:setup

i get below error

triggering load callbacks * 2015-07-15 17:00:06 17:00:06 == Currently executing `deploy:setup' * executing multiple commands in parallel -> "else" :: "mkdir -p /srv/playdrone /srv/playdrone/releases /srv/playdrone/shared /srv/playdrone/shared/system /srv/playdrone/shared/log /srv/playdrone/shared/pids" -> "else" :: "mkdir -p /srv/playdrone /srv/playdrone/releases /srv/playdrone/shared /srv/playdrone/shared/system /srv/playdrone/shared/log /srv/playdrone/shared/pids" -> "else" :: "mkdir -p /srv/playdrone /srv/playdrone/releases /srv/playdrone/shared /srv/playdrone/shared/system /srv/playdrone/shared/log /srv/playdrone/shared/pids" servers: ["node01.playdrone.io", "node02.playdrone.io", "node03.playdrone.io"] connection failed for: node03.playdrone.io (SocketError: getaddrinfo: nodename nor servname provided, or not known),node02.playdrone.io (SocketError: getaddrinfo: nodename nor servname provided, or not known), node01.playdrone.io (SocketError: getaddrinfo: nodename nor servname provided, or not known)

so from what i understand i just copied a code from open source and it looks like those guys are using playdrone.io server.

i being a dumb guy copied the same code and got this error. So i created a virtual machine with mac osx and now i want to use it as server and run jobs from my main macbook(my system)

what are the roles i need to use like role:unicorn....role:sidekiq and so on....

i donno capistrano at all and so on...please help. can i use virtual machine as a server ?

it would be very helpful if you could clear my doubts..thanks soo much


regards,
sooraj
