### ISSUE TITLE
directory permissions of dist

### ISSUE THREAD

**Issue by leoj3n** [roots/roots-example-project.com#22]
The [config here](https://github.com/roots/roots-example-project.com/blob/98aa8749294e48edf16c8667535992f12a8dd29d/ansible/group_vars/production#L11-L22) seems to create a local directory with permissions `drwx------` and upload that to the server with those same permissions which the web user is not able to access.

SSHing into the server and running

`chmod -R 755 /srv/www/example.com/current/web/app/themes/sage/dist`

fixes the 404s.

**Comment by austinpray** [comment]
So the [syncronize](https://docs.ansible.com/ansible/synchronize_module.html) module uses the `-a` flag by default. This means it will preserve the permissions from your computer when syncing to the remote. 

Check your local computer permissions are set to 755.

We could mitigate this issue by setting `perms` to no.

**Comment by swalkinshaw** [comment]
We should be explicitly setting the remote permissions if possible. The local permissions have no value in this case.

**Comment by swalkinshaw** [comment]
This belongs over at Trellis: https://github.com/roots/trellis/issues/303
