### ISSUE TITLE
Site Missing Styling

### ISSUE THREAD

**Issue by BrandonShutter** [roots/roots-example-project.com#27]
Fyi, the site right now isn't working for travelers that come across it.

**Comment by swalkinshaw** [comment]
http://roots-example-project.com looks fine? That's just default Sage.

**Comment by BrandonShutter** [comment]
![roots example](https://cloud.githubusercontent.com/assets/2022885/9736083/2fd26e2c-560d-11e5-9150-4555df386c3d.jpg)
I've never used Sage, but this is the default look?  My apologies if so.

**Comment by swalkinshaw** [comment]
Yep. It's amazing anyone uses Sage when it looks like that :)

It's just default Bootstrap without any components used.
