### ISSUE TITLE
Outdated Trellis hooks

### ISSUE THREAD

**Issue by bokorir** [roots/roots-example-project.com#31]
Based on our conversation on [Roots Discourse](https://discourse.roots.io/t/deployment-with-the-new-trellis-hooks) I'm opening a ticket here about the outdated documentation/project files. Trellis now uses different hook names/structure so it would be good to update this project or release a new version with the new standards.

Thanks

**Comment by swalkinshaw** [comment]
For anyone who comes across this before we update it. See https://discourse.roots.io/t/deployment-with-the-new-trellis-hooks/5016/2
