### ISSUE TITLE
ansible fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by imcodingideas** [roots/roots-example-project.com#32]
I'm getting a error:

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

and it's specifically in the ansible bit.

Clone Trellis: $ git clone --depth=1 git@github.com:roots/trellis.git ansible && rm -rf ansible/.git

**Comment by retlehs** [comment]
you need to add your public key to github in order to clone public repos via ssh.

please use https://discourse.roots.io/ for support in the future (and please search before posting)

**Comment by marijnbent** [comment]
I had the same issue while I already added a public key. Adding https did help:
https://git@github.com/roots/trellis.git
