### ISSUE TITLE
Missing trellis/group_vars/development/vault.yml

### ISSUE THREAD

**Issue by omargourari** [roots/roots-example-project.com#36]
Is there any reason why there's no vault.yml file in this repo?

**Comment by swalkinshaw** [comment]
Yes, we haven't updated it yet to match the latest Trellis.

**Comment by itsazzad** [comment]
will it work then?

**Comment by retlehs** [comment]
this repo will work if you clone it and use it, it's just not using the latest version of trellis right now. you can follow the steps in the readme to get the latest versions of everything instead of cloning down this repo
