### ISSUE TITLE
node_module install fail

### ISSUE THREAD

**Issue by dealion** [roots/roots-example-project.com#40]
Mac 10.7.5
NPM v3.8.6
Node v5.10.1

> fsevents@1.0.11 install /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> node-sass@3.4.2 install /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/node-sass/vendor/darwin-x64-47/binding.node

> spawn-sync@1.0.15 postinstall /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/spawn-sync
> node postinstall
> 
> node-sass@3.4.2 postinstall /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/node-sass
> node scripts/build.js

`/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/node-sass/vendor/darwin-x64-47/binding.node` exists.
 testing binary.
Binary is fine; exiting.

> pngcrush-bin@3.0.0 postinstall /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/pngcrush-bin
> node lib/install.js

  ⚠ The `/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/optipng-bin/vendor/optipng` binary doesn't seem to work correctly
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✔ optipng built successfully

> jpegtran-bin@3.0.6 postinstall /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ The `/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/jpegtran-bin/vendor" --bindir="/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/jpegtran-bin/vendor" --bindir="/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/jpegtran-bin/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:475:12)
```

> gifsicle@3.0.3 postinstall /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/gifsicle
> node lib/install.js

⚠ The `/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/gifsicle/vendor/gifsicle` binary doesn't seem to work correctly
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/gifsicle/vendor" --bindir="/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/gifsicle/vendor" && make install
Command failed: autoreconf -ivf
/bin/sh: autoreconf: command not found

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:475:12)
```

**Comment by retlehs** [comment]
https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060
