### ISSUE TITLE
Setup query

### ISSUE THREAD

**Issue by nickeblewis** [roots/roots-example-project.com#41]
Hi there - I have run through the setup on the Readme and all of that went fine, until I try to view the site but I am getting a page not found error.... I have added an entry to my hosts file, as:

192.168.50.5 roots-example-project.dev

But no luck - what could I be missing? What am I doing wrong?

Thanks,

Nick

**Comment by paultibbetts** [comment]
Hi Nick, 

If you're using Trellis then the `vagrant-hostmanager` plugin will update your hosts file for you so you shouldn't need to add anything manually; however the team uses GitHub issues for bug reports so you're much more likely to get some help with this if you open a thread on the forums at https://discourse.roots.io

**Comment by swalkinshaw** [comment]
Please use https://discourse.roots.io for support questions as @ptibbetts mentioned.
