### ISSUE TITLE
Permission denied (publickey) when i clone trellis

### ISSUE THREAD

**Issue by dotMastaz** [roots/roots-example-project.com#42]
Hello,
When i clone Trellis: $ git clone --depth=1 git@github.com:roots/trellis.git && rm -rf trellis/.git
i have this : 
Cloning into 'trellis'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Thank you for your help !!

**Comment by retlehs** [comment]
https://help.github.com/articles/generating-an-ssh-key/

please don't use github for support. see https://discourse.roots.io/
