### ISSUE TITLE
Ansible error on El Capitan

### ISSUE THREAD

**Issue by slip** [roots/roots-example-project.com#43]
Here is the error: ERROR! Unexpected Exception: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=11.3'))

Here is how to fix it: 'pip install --upgrade setuptools --user python'

Might want to update the Readme.

**Comment by retlehs** [comment]
getting more specific on ansible installation isn't really related to this repo

**Comment by slip** [comment]
Depending on how many folks are on El Capitan and trying to follow your Local Development Setup section of your Readme…

**Comment by retlehs** [comment]
then hopefully they will learn excellent searching/debugging skills to figure it out before diving into our projects

**Comment by retlehs** [comment]
ps. you can always PR http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-pip if you feel strongly about it. that's what we link to in our README.

**Comment by slip** [comment]
totes. why document a one line fix for a large portion of your userbase when we have google.

btw, that's what i used to install ansible. i'll take it up with them.
