### ISSUE TITLE
SSH Error: data could not be sent to remote host "roots-example-project.com". Make sure this host can be reached over ssh

### ISSUE THREAD

**Issue by AnythingLinux** [roots/roots-example-project.com#67]
System info:
  Ansible 2.7.5; Linux
  Trellis 1.0.1: January 16th, 2019
---------------------------------------------------
SSH Error: data could not be sent to remote host "roots-example-project.com".
Make sure this host can be reached over ssh
fatal: [roots-example-project.com]: UNREACHABLE! => {"changed": false, "unreachable": true}
	to retry, use: --limit @/home/username/roots-example-project.com/trellis/deploy.retry

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
roots-example-project.com  : ok=1    changed=0    unreachable=1    failed=0   
![screenshot from 2019-03-04 05-10-38](https://user-images.githubusercontent.com/1058663/53703403-df307c00-3e3b-11e9-8367-c2ecc90e8ea6.png)

**Comment by retlehs** [comment]
you're not gonna have permission to connect to roots-example-project.com via SSH

https://github.com/roots/roots-example-project.com/blob/c7a42850990cacc3bba1cc2b8791a75635e59037/trellis/group_vars/all/users.yml#L12-L14

the server is provisioned with keys from a few of us on the roots team. this is an example repo and you'll need to replace `roots-example-project.com` in the codebase with your own domain.

please follow the README/docs and join us at https://discourse.roots.io/ if you have further questions!
