### ISSUE TITLE
yarn fails to run

### ISSUE THREAD

**Issue by hemang-ajmera** [roots/roots-example-project.com#76]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing issue
* [ x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
yarn fails with below error

Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

## Steps to reproduce

1. Do fresh windows setup as mentioned in https://roots.io/getting-started/docs/development-environment-recommendations/
2. Clone repository
3. Run composer install
4. run yarn

**Expected behavior:** 
No error

**Actual behavior:** 
Error as mentioned above

**Reproduces how often:**
Always

**Comment by movila** [comment]
all packages are outdated, so you probably need to run `yarn upgrade` before `yarn`

**Comment by retlehs** [comment]
👋  please post on https://discourse.roots.io/ for support
