### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by stopspazzing** [roots/roots-example-project.com#8]
`# git clone --depth=1 git@github.com:roots/bedrock-ansible.git ansible && rm -rf ansible/.git`                Cloning into 'ansible'...  
The authenticity of host 'github.com (192.30.252.131)' can't be established.  
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.  
Are you sure you want to continue connecting (yes/no)? yes  
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.  
Permission denied (publickey).  
fatal: Could not read from remote repository.  
Please make sure you have the correct access rights                                                                                                             and the repository exists.

**Comment by austinpray** [comment]
> Please make sure you have the correct access rights and the repository exists.

https://help.github.com/articles/generating-ssh-keys/

**Comment by stopspazzing** [comment]
Cant believe i forgot to add ssh key for my server.. Thanks!!
