### ISSUE TITLE
Ansible issue

### ISSUE THREAD

**Issue by BenjaminWaye** [roots/roots-example-project.com#81]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing issue
* [ x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Started up Roots example project which first needed a yarn update and a couple of fixes to the node-sass in order to build.

Finally once I got to the vagrant part I get an Ansible error. So I add the shared file fix into the config.yml. And it runs. But there is no website? There is no localhost, the url https://roots-example-project.test/

Gives a This site can’t be reached roots-example-project.test’s server IP address could not be found. DNS_PROBE_FINISHED_NXDOMAIN

Has anyone had a similar bug?

This is the only stack trace I’m getting all looks good but nothing is happening.

trellis % vagrant up
Bringing machine ‘default’ up with ‘virtualbox’ provider…
==> default: Checking if box ‘bento/ubuntu-18.04’ version ‘202010.24.0’ is up to date…
==> default: Clearing any previously set forwarded ports…
==> default: Clearing any previously set network interfaces…
==> default: Preparing network interfaces based on configuration…
default: Adapter 1: nat
default: Adapter 2: hostonly
==> default: Forwarding ports…
default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running ‘pre-boot’ VM customizations…
==> default: Booting VM…
==> default: Waiting for machine to boot. This may take a few minutes…
default: SSH address: 127.0.0.1:2222
default: SSH username: vagrant
default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM…
==> default: Setting hostname…
==> default: Configuring and enabling network interfaces…
==> default: Exporting NFS shared folders…
==> default: Preparing to edit /etc/exports. Administrator privileges will be required…
Password:
==> default: Mounting NFS shared folders…
==> default: Mounting shared folders…
default: /vagrant => /Users/benjaminwaye/Sites/roots-example-project.com/trellis
==> default: Machine already provisioned. Run vagrant provision or use the --provision
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running action triggers after up …
==> default: Running trigger…
==> default: Adding vagrant ssh-config for roots-example-project.test to ~/.ssh/config

==> default: Machine ‘default’ has a post vagrant up message. This is a message
==> default: from the creator of the Vagrantfile, and not from Vagrant itself:
==> default:
==> default: Your Trellis Vagrant box is ready to use!
==> default: * Composer and WP-CLI commands need to be run on the virtual machine
==> default: for any post-provision modifications.
==> default: * You can SSH into the machine with vagrant ssh.
==> default: * Then navigate to your WordPress sites at /srv/www
==> default: or to your Trellis files at /home/vagrant/trellis.

## Steps to reproduce

1.  Follow instructions.
2. Fix all the errors that pop up
3. Pray to whatever diety you hold dear

**Expected behavior:** 

It would work and let me access root-example-project.test

**Actual behavior:**

The above stack trace and no error and no site.

**Reproduces how often:** Every time

## Versions

Mac OS Catalina 10.15.7
latest version of the project

**Comment by retlehs** [comment]
👋  please post on https://discourse.roots.io/ for support
