### ISSUE TITLE
Development site not available for Windows WSL2

### ISSUE THREAD

**Issue by hstandeffer** [roots/roots-example-project.com#89]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

[Description of the issue]
I've followed the steps and tried plenty of different versions, configurations etc. with no luck on getting the dev site up and running properly on WSL2

## Steps to reproduce

1. Clone repo
2. install theme
3. vagrant up

**Expected behavior:** [What you expect to happen]
The site is expected to be available at the local address

**Actual behavior:** [What actually happens]
I'm sent to a google search of the web url as nothing loads

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time
## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by retlehs** [comment]
👋  please post on https://discourse.roots.io/ for support
