### ISSUE TITLE
Missing composer installation requirement

### ISSUE THREAD

**Issue by stopspazzing** [roots/roots-example-project.com#9]
If following the instructions on a fresh server, under Sage/Theme

Add Soil: $ cd site && composer require roots/soil

Composer doesn't exist as it's not listed under requirements to continue, nor is i listed in Sage/Theme requirements, so continuing is not possible. Could you please update the requirements?

https://getcomposer.org/doc/00-intro.md or to globally install:

```
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
```

**Comment by austinpray** [comment]
So if you are talking about remote servers: it is not an external requirement for this repo as it is automatically installed when you provision the server with ansible.

If you are talking about locally running operations on the vagrant host machine which then get synced to the vagrant box, I suppose you are right.

Instructions need to be added here: https://github.com/roots/bedrock#requirements. I don't see anything super wrong with adding the composer requirement to the soil section of this repo's readme as a by-the-way. Shoot us some pull requests.

**Comment by QWp6t** [comment]
Should definitely be in the Bedrock section of the README.md in this repo imo. Should also be added to bedrock repo, as apray suggested.

**Comment by stopspazzing** [comment]
Added 2 pull requests with link to install composer if user hasn't yet. 

Still this issue:

`# cd ansible && ansible-galaxy install -r requirements.yml`
downloading role 'project_deploy_module', owned by -%20src%3A%20f500
Sorry, - src: f500.project_deploy_module was not found on galaxy.ansible.com.
downloading role '-%20name%3A%20ntp', owned by
Sorry, - name: ntp was not found on galaxy.ansible.com.
downloading role 'ntp', owned by src%3A%20resmo
Sorry, src: resmo.ntp was not found on galaxy.ansible.com.
downloading role '-%20name%3A%20logrotate', owned by
Sorry, - name: logrotate was not found on galaxy.ansible.com.
downloading role 'logrotate', owned by src%3A%20nickhammond
Sorry, src: nickhammond.logrotate was not found on galaxy.ansible.com.
downloading role '-%20name%3A%20php5-xdebug', owned by
Sorry, - name: php5-xdebug was not found on galaxy.ansible.com.
downloading role 'php5-xdebug', owned by src%3A%20MaximeThoonsen
Sorry, src: MaximeThoonsen.php5-xdebug was not found on galaxy.ansible.com.

**Comment by austinpray** [comment]
@stopspazzing check your ansible version

**Comment by stopspazzing** [comment]
@austinpray After successfully upgrading ansible with pip from 1.7.2 to 1.9.1 (latest), same issue.

**Comment by swalkinshaw** [comment]
I added Composer as a requirement to Bedrock [here](https://github.com/roots/bedrock/commit/44601b69f0c29b6e10d2d7f7c0b92e8b97c08425).

But we could just change this step to manually edit the `composer.json` file. Little harder but then doesn't require Composer locally.

**Comment by austinpray** [comment]
@swalkinshaw ben's suggestion was to add `vagrant ssh` as the first step.

Might be good idea because it doesn't require installing composer in your path and stuff
