### ISSUE TITLE
Bug: `requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0]` on `composer install`

### ISSUE THREAD

**Issue by strarsis** [roots/roots-example-project.com#93]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
When trying to install the `composer` dependencies using `composer` `v2` (which recent `Trellis` also does, hence it also causes a deployment error there), `composer` fails to install the dependencies because the `composer.json` expects `composer-plugin-api` `v1.x` while `composer` `v2` has the `composer-plugin-api` `v2.x`.

#### What have you tried?
`composer install` inside the `site/` directory of this repository.

#### What insights have you gained?
Incompatibilities with `composer` `v2` which is the current version and also used in recent `Trellis`.

#### Possible solutions
Update the `composer` dependencies / update the `composer.lock` lockfile.

### Steps To Reproduce

A.
1. Use this repository as a Trellis site (`repo: git@github.com:roots/roots-example-project.com.git`).
2. Deploy the site, note that Trellis deployment fails.

B.
1. Clone this repository (e.g. `git clone git@github.com:roots/roots-example-project.com.git`).
2. Go into the `site/` directory (`cd roots-example-project.com/site`.
3. Invoke `composer install`.
Note the error that occurs.

### Expected Behavior

No `composer` errors when installing the dependencies using `composer install`.

### Actual Behavior

`composer` error when using `composer install`.

### Relevant Log Output

```shell
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - composer/installers is locked to version v1.6.0 and an update of this package was not requested.
    - composer/installers v1.6.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
  Problem 2
    - roots/wordpress-core-installer is locked to version 1.1.0 and an update of this package was not requested.
    - roots/wordpress-core-installer 1.1.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
  Problem 3
    - composer/installers v1.6.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - roots/wp-password-bcrypt 1.0.0 requires composer/installers ~1.0 -> satisfiable by composer/installers[v1.6.0].
    - roots/wp-password-bcrypt is locked to version 1.0.0 and an update of this package was not requested.
```

### Versions

* Update to WordPress 5.2 ([#432](https://github.com/roots/bedrock/pull/432))

**Comment by strarsis** [comment]
So I started updating `Bedrock` and `Sage` in the example project.
For updating Trellis I noticed that `trellis` ([`Trellis CLI`](https://github.com/roots/trellis-cli) now has a [`trellis new`](https://github.com/roots/trellis#installation:~:text=%24-,trellis%20new,-example.com) command that creates the whole example project, including a bedrock site. Except for Sage, but there is a simple `composer create-project roots/sage sage dev-main` command for that (inside the `site/web/app/themes/` directory).

This should be added as a note to this project: For getting the most recent and working (with `composer` `v2`) example project, use `trellis new` from `Trellis CLI`, and `composer create-project roots/sage sage dev-main` inside `site/web/app/themes/` of the directory newly created by `trellis`.

**Comment by swalkinshaw** [comment]
We've talked about just retiring this repo entirely since we aren't sure how useful it is.

Do you use this as a template?

**Comment by strarsis** [comment]
@swalkinshaw: I don't know if this already exists (and I simply missed it), but it would be great if the Trellis repository [`wordpress_sites.yml`](https://github.com/roots/trellis/blob/master/group_vars/production/wordpress_sites.yml#L12) uses a real, recent Bedrock example site (the currently used `git@github.com:example/example.com.git` repository doesn't exist).
This helps with testing deployments from an unchanged Trellis, otherwise an empty Bedrock site repository needs to be created first. It would be great if the example there would just deploy an empty but recent Bedrock site.

Edit: Maybe not for production (due to security reasons, as someone may accidentally deploy an empty site to production), but for `staging` this would be quite useful.

**Comment by strarsis** [comment]
@swalkinshaw: Edit 2: The [Bedrock repository](https://github.com/roots/bedrock) itself could be used as the example site?

**Comment by swalkinshaw** [comment]
It can be... I actually use it locally for testing. I think I just wanted `git@github.com:example/example.com.git` to be obvious that it should be replaced. 1) since it's clearly a placeholder, and 2) it would fail anyway

Maybe it doesn't matter much since there's already a comment (and docs)

**Comment by strarsis** [comment]
OK, so IMHO this repository can be retired as it is quite outdated now and `trellis new` offers a way to create an example project with Trellis + Bedrock that is recent. 

Edit: The Bedrock repo can be added as _comment_ to the example site in Trellis on production and staging. So it is very easy to copy/enable it if Trellis deployments should be tested quickly.
